# Generated by Django 4.1.5 on 2023-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('uy_haqida', models.TextField()),
                ('narhi', models.IntegerField(max_length=200)),
                ('necha_hona', models.IntegerField(max_length=200)),
                ('kvadrati', models.IntegerField(max_length=200)),
                ('manzil', models.CharField(choices=[('Qoraqalpog‘iston Respublikasi', ((1, 'Nukus shahri'), (2, 'Amudaryo tumani'), (3, 'Beruniy tumani'), (3, 'Kegeyli tumani'), (3, 'Qanliko‘l tumani'), (3, 'Qorao‘zak tumani'), (3, 'Qo‘ng‘irot tumani'), (3, 'Mo‘ynoq tumani'), (3, 'Nukus tumani'), (3, 'Taxiatosh tumani'), (3, 'Taxtako‘pir tumani'), (3, 'To‘rtko‘l tumani'), (3, 'Xo‘jayli tumani'), (3, 'Chimboy tumani'), (3, 'Sho‘manoy tumani'), (3, 'Ellikqal’a tumani'))), ('Andijon viloyati', ((4, 'Andijon shahri'), (4, 'Xonabod shahri'), (4, 'Andijon tumani'), (4, 'Asaka tumani'), (4, 'Baliqchi tumani'), (4, 'Bo‘z tumani'))), ('Uttar Pradesh', ((6, 'Lucknow'), (7, 'Agra')))], max_length=200)),
            ],
        ),
    ]
