# Generated by Django 4.1.5 on 2023-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='kvadrati',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='narhi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='necha_hona',
            field=models.IntegerField(),
        ),
    ]
