# Generated by Django 4.1.5 on 2023-09-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_categoryviloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='voliyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.categoryviloyat'),
        ),
    ]
