# Generated by Django 4.1.5 on 2023-09-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_house_voliyat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='voliyat',
            new_name='voliyat2',
        ),
    ]
