# Generated by Django 4.1.5 on 2023-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_rename_voliyat_house_voliyat2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='voliyat2',
        ),
        migrations.AddField(
            model_name='house',
            name='voliyat',
            field=models.CharField(choices=[('Qoraqalpog‘iston Respublikasi', 'Qoraqalpog‘iston Respublikasi'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Farg‘ona viloyati', 'Farg‘ona viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Toshkent shahri', 'Toshkent shahri')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
