# Generated by Django 4.1.5 on 2023-09-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_remove_house_voliyat2_house_voliyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='voliyat',
        ),
    ]
