# Generated by Django 4.1.5 on 2023-09-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_house_voliyatingiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoryviloyat',
        ),
    ]
