# Generated by Django 4.1.5 on 2023-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_delete_categoryviloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='asosiy_rasm',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='qoshimcha_rasm1',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='qoshimcha_rasm2',
            field=models.ImageField(default=2, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='qoshimcha_rasm3',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
