# Generated by Django 4.1.5 on 2023-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_house_asosiy_rasm_house_qoshimcha_rasm1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='raqam',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
