# Generated by Django 4.1.5 on 2023-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_alter_house_manzil_alter_house_voliyatingiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='raqam',
            field=models.CharField(max_length=200),
        ),
    ]
